version: '2'
services:

  zookeeper:
    image: biggis/zookeeper:3.4.6
    restart: always
    hostname: zookeeper
    ports:
      - "${ZOOKEEPER_PORT:2181}:2181"
    environment:
      USER_ID: ${UID}
      USER_NAME: zookeeper
    volumes:
      - zookeeper-data:/tmp/zookeeper/data

  kafka:
    image: biggis/kafka:0.9.0.0
    restart: always
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA_PORT:9092}:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP:127.0.0.1}
      USER_ID: ${UID}
      USER_NAME: kafka
    volumes:
      - kafka-data:/tmp/kafka/data

  postgres:
    image: biggis/postgres:9.6-alpine
    restart: always
    hostname: postgres
    ports:
      - "${POSTGRES_PORT:5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:postgres}
      POSTGRES_USER: ${POSTGRES_USER:postgres}
      POSTGRES_PW: ${POSTGRES_PW:postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata

  pgadmin:
    image: fenglc/pgadmin4:1.1
    restart: always
    hostname: pgadmin4
    environments:
      PORT: ${PGADMIN_PORT:5050}
    volumes:
      - pgadmin-data:/root/.pgadmin

  consumer-postgres:
    image: smueller18/consumer:postgres
    restart: always
    hostname: consumer-postgres
    environments:
      POSTGRES_HOST: ${POSTGRES_HOST:postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:5432}
      POSTGRES_DB: ${POSTGRES_DB:postgres}
      POSTGRES_USER: ${POSTGRES_USER_CONSUMER:postgres}
      POSTGRES_PW: ${POSTGRES_PW_CONSUMER:postgres}
      CONSUMER_GROUP: ${CONSUMER_GROUP:postgres}
      AUTO_COMMIT_INTERVAL: ${AUTO_COMMIT_INTERVAL:5000}
      LOGGING_LEVEL: ${LOGGING_LEVEL:INFO}
      LOGGING_FORMAT: ${LOGGING_FORMAT:"%(message)s"}

  consumer-monitor:
    image: smueller18/consumer:monitor
    restart: always
    hostname: consumer-monitor
    environments:
      PORT: ${MONITOR_PORT:5000}
      TOPIC: ${MONITOR_TOPIC:chillii}
      CONSUMER_GROUP: ${CONSUMER_GROUP:monitor}
      AUTO_COMMIT_INTERVAL: ${AUTO_COMMIT_INTERVAL:60000}
      LOGGING_LEVEL: ${LOGGING_LEVEL:INFO}
      LOGGING_FORMAT: ${LOGGING_FORMAT:"%(message)s"}

volumes:
  zookeeper-data:
  kafka-data:
  postgres-data:
  pgadmin-data:
